#!/bin/bash
DIR=$(pwd)			


if [ "$1" == "clean" ] 
then	
	echo "Clean up.."
	rm -rfv B_Plus_Tree/build/*

else
	if [ "$1" != "" ]
	then
		echo "Ignoring extra arguments.."
	fi
	echo "Running project.."
	echo "CMake Building for B+ Tree.."
	cd B_Plus_Tree
	mkdir build
	cd build
	cmake ..
	echo "CMake Build done"
	echo "Build project..."
	make
	echo "Build done..."

	./BPlusTree 



fi


